### ISSUE TITLE
pull next_player and turns_left into game_state

### ISSUE THREAD

**Issue by TimoFreiberg** [Alexander-Miller/hanabi-server#5]
because it makes handling the same structures in haskell a bit nicer

**Comment by Alexander-Miller** [comment]
just use dyadic functile hyperarrows
its like, totally elegant and stuff

**Comment by TimoFreiberg** [comment]
[No results found for "dyadic functile hyperarrows" haskell.](https://www.google.de/search?q=%22dyadic+functile+hyperarrows%22+haskell&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=zt98WIrGGZHEXonjr_AO)

**Comment by Alexander-Miller** [comment]
its lazy and will on appear when actually used

**Comment by Alexander-Miller** [comment]
done
