### ISSUE TITLE
Panic at game start (Option::unwrap)

### ISSUE THREAD

**Issue by TimoFreiberg** [Alexander-Miller/hanabi-server#8]
At main.rs:31
Log attached: [hanabi-server.txt](https://github.com/Alexander-Miller/hanabi-server/files/785050/hanabi-server.txt)

**Comment by Alexander-Miller** [comment]
[ 9 of 11] Compiling Hanabi.Client    ( src/Hanabi/Client.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Hanabi/Client.o )
               
/home/a/Documents/git/hanabi-client-hs/src/Hanabi/Client.hs:83:21: error:
    Not in scope: ‘Cli.handleInput’
    Module ‘Hanabi.Client.Cli’ does not export ‘handleInput’.
               
/home/a/Documents/git/hanabi-client-hs/src/Hanabi/Client.hs:85:11: error:
    Not in scope: data constructor ‘SendRequest’
    Perhaps you meant ‘Cli.SendRequest’ (imported from Hanabi.Client.Cli)
               
/home/a/Documents/git/hanabi-client-hs/src/Hanabi/Client.hs:86:11: error:
    Not in scope: data constructor ‘InputErr’
    Perhaps you meant ‘Cli.InputErr’ (imported from Hanabi.Client.Cli)
Completed 72 action(s).

--  While building package hanabi-0.1.0.0 using:
      /home/a/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:hanabi exe:hanabi-exe --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by TimoFreiberg** [comment]
https://github.com/TimoFreiberg/hanabi/commit/10ded7e0667c34cb23bf42e6cad50903bf20129e ;)

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/hanabi-server/commit/7a8f4962ed1831a62ba39d183c4456e64155b318 ;o)
